Blog/Blog/blog/urls.py
from django.urls import path
from . import views


app_name = "blog"

urlpatterns = [
    path("", views.index, name="index"),
    path("post/<str:slug>/", views.details, name="details"),
    # path("new_different_url", views.new_url_redirect, name="new_url"),
    # path("old_url", views.old_url, name="old_url"),
    path("contact/", views.contact, name="contact"),
    path("about/", views.about, name="about"),
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("logout/", views.logout_user, name="logout"),
    path("forgot_password", views.forgot_password, name="forgot_password"),
    path("reset_password/<uidb64>/<token>", views.reset_password, name="reset_password"),
    path("new_post/", views.new_post, name="new_post"),
    path("edit_post/<int:post_id>", views.edit_post, name="edit_post"),
    path("delete_post/<int:post_id>", views.delete_post, name="delete_post"),
    path("publish_post/<int:post_id>", views.publish_post, name="publish_post"),
]

Blog/Blog/mydjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

handler404 = 'mydjango.views.custom_error_page'

urlpatterns = [
    path("", include("blog.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Blog/Blog/blog/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User


class Category(models.Model):
	name = models.CharField(max_length=200)

	def __str__(self):
		return self.name


# Create your models here.
class Post(models.Model):
	title = models.CharField(max_length=200)
	content = models.TextField()  
	img_url = models.ImageField(null=True, upload_to="posts/images")
	created_at = models.DateTimeField(auto_now_add=True)
	slug = models.SlugField(unique=True)
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
	is_published = models.BooleanField(default=False)

	def save(self, *args, **kwargs):
		self.slug = slugify(self.title)
		super().save(*args, **kwargs)

	def formatted_url(self):
		url = self.img_url if self.img_url.__str__().startswith(("http", "https")) else self.img_url.url
		return url

	def __str__(self):
		return self.title

class AboutUs(models.Model):
	content = models.TextField()
	

Blog/Blog/blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate

from blog.models import Category, Post

class ContactForm(forms.Form):

    name = forms.CharField(label='Name', max_length=50, required=True)
    email = forms.EmailField(label='Email', required=True)
    message = forms.CharField(max_length=200, label='Message', required=True)
    
class RegisterForm(forms.ModelForm):
    username = forms.CharField(label="Username", max_length=50, required=True)
    email = forms.CharField(label="Email", max_length=50, required=True)
    password = forms.CharField(label="Password", max_length=50, required=True)
    confirm_password = forms.CharField(label="Confirm Password", max_length=50, required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("Passwords do not match")
        # if not password:
        #     raise forms.ValidationError("Password should not be empty")
        if password and len(password) < 8:
            raise forms.ValidationError("Password length should be more than 8 Characters")
        
class LoginForm(forms.Form):
    username = forms.CharField(label="Username", max_length=50, required=True)
    password = forms.CharField(label="Password", max_length=50, required=True)

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        password = cleaned_data.get("password")

        if username and password:
            user = authenticate(username = username, password = password)
            if user is None:
                raise forms.ValidationError("Invalid username and password")
            
class ForgotPassword(forms.Form):
    email = forms.CharField(label='email', max_length=50)
    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')

        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError("User doesn't exist")
        
class ResetPassword(forms.Form):
    new_password = forms.CharField(label='New Password', min_length=8)
    confirm_password = forms.CharField(label='Confirm Password', min_length=8)

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get('new_password')
        confirm_password = cleaned_data.get('confirm_password')

        if new_password and confirm_password and new_password != confirm_password:
            raise forms.ValidationError("Passwords doesn't match")

class NewPostForm(forms.ModelForm):
    title = forms.CharField(max_length=20, label="Title", required=True)
    content = forms.CharField(label="Content", required=True)
    category = forms.ModelChoiceField(label="Category", required=True, queryset=Category.objects.all())
    img_url = forms.ImageField(label='Upload Image', required=False)

    class Meta():
        model = Post
        fields = ['title', 'content', 'category', 'img_url']

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get('title')
        content = cleaned_data.get('content')

        if title and len(title) < 5:
            raise forms.ValidationError("Title must be atlease 5 characters long")
        
        if content and len(content) < 10:
            raise forms.ValidationError("Content must be 10 characters long")
        
    def save(self, commit = ...):
        post = super().save(commit)
        cleaned_data = super().clean()

        if cleaned_data.get('img_url'):
            post.img_url = cleaned_data.get('img_url')
        else:
            img_url = "https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg"
            post.img_url = img_url
            
        if commit == True:
            post.save()
        return post

Blog/Blog/blog/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from django.urls import reverse
import logging
from .models import Category, Post, AboutUs
from django.core.paginator import Paginator
from .forms import ContactForm, ForgotPassword, NewPostForm, RegisterForm, LoginForm, ResetPassword
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login, logout
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
# Create your views here.

# posts = [{'id': 1, 'title': 'Post 1', 'content': 'This is post 1', 'game': 'Foortball'},
#         {'id': 2, 'title': 'Post 2', 'content': 'This is post 2', 'game': 'Cricket'},
#         {'id': 3, 'title': 'Post 3', 'content': 'This is post 3', 'game': 'Chess'},
#         {'id': 4, 'title': 'Post 4', 'content': 'This is post 4', 'game': 'Hockey'},
#         ]

def index(request):
    name = "Latest"
    all_posts = Post.objects.filter(is_published = True)

    #Paginate
    paginator = Paginator(all_posts, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'index.html', {'Name': name, 'page_obj': page_obj})


def details(request, slug):
    if request.user and not request.user.has_perm('blog.view_post'):
        messages.error(request=request, message="You don't have permission to view")
        return redirect('blog:index')
    post = Post.objects.get(slug=slug)
    related_post = Post.objects.filter(category = post.category).exclude(id = post.id)
    if not related_post:
        related_post.title = "No related posts"
        related_post.url = ""
        print(related_post)
    #Static data
    # post = next((item for item in posts if item['id'] == int(post_id)), None)
    # logger = logging.getLogger("Test")
    # logger.debug("error"+post)
    # logger.debug("error"+Post)
    return render(request, "detail.html", {'post' : post, 'related_posts': related_post})

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        # form.cleaned_data['name']
        logger = logging.getLogger("Test")
        if form.is_valid():
            logger.debug(f"DATA {form.cleaned_data['name']} {form.cleaned_data['email']} {form.cleaned_data['message']}")
            success_message = "Your request is submitted"
            return render(request, "contact.html", {'form': form, 'success': success_message})
        # else:
        #     logger.debug("Invalid Form")
        return render(request, "contact.html", {'form': form, 'name': name, 'email': email, 'message': message})
    return render(request, "contact.html")

def about(request):
    about_content = AboutUs.objects.first()
    # print(about_content)
    if about_content is None or not about_content.content:
        about_content = "This is default message"
    else:
        about_content = about_content.content
    return render(request, "about.html", {'about_content': about_content})
# def old_url(request):
#     return redirect(reverse("blog:new_url"))


# def new_url_redirect(request):
#     return HttpResponse("New url")
def register(request):
    form = RegisterForm()
    if request.method == 'POST':
        form  = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit = False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            readers_group, created = Group.objects.get_or_create(name="Readers")
            user.groups.add(readers_group)
            messages.success(request, "Registration successful!")
            return redirect("/login")
    return render(request, 'register.html', {'form': form})

def login(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password = password)
            print("user")
            if user is not None:
                auth_login(request, user)
                print("success")
                return redirect("/dashboard")
    return render(request, 'login.html', {'form': form})

def dashboard(request):
    blog_title = "My blog"
    all_posts = Post.objects.filter(user = request.user)
    paginator = Paginator(all_posts, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, "dashboard.html", {'blog_title': blog_title, 'page_obj': page_obj})

def logout_user(request):
    logout(request)
    return redirect('blog:index')

def forgot_password(request):
    form = ForgotPassword()
    if request.method == 'POST':
        form = ForgotPassword(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            user = User.objects.get(email=email)
            token = default_token_generator.make_token(user)
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            current_site = get_current_site(request)
            subject = "Reset Password"
            domain = current_site.domain
            message = render_to_string('reset_password_mail.html',{
                "domain": domain,
                'uid': uid,
                'token': token
            })
            send_mail(subject=subject, message=message, from_email='noreply@test.com', recipient_list=[email])
            messages.success(request, 'Email has been sent')

    return render(request, 'forgot_password.html', {'form': form})

def reset_password(request, uidb64, token):
    form = ResetPassword()
    if request.method == 'POST':
        form = ResetPassword(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data['new_password']
            try:
                uid = urlsafe_base64_decode(uidb64)
                user = User.objects.get(pk = uid)
            except(TypeError, ValueError, User.DoesNotExist, OverflowError):
                user = None
            if user is not None and default_token_generator.check_token(user, token):
                user.set_password(new_password)
                user.save()
                messages.success(request=request, message="Your Password has been reset successfully")
                return redirect('blog:login')
            else:
                messages.error(request, 'The reset link is invalid')
    return render(request, 'reset_password.html', {'form': form})

@login_required
def new_post(request):
    categories = Category.objects.all()
    form = NewPostForm()
    if request.method == 'POST':
        form = NewPostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('blog:dashboard')
    return render(request, 'new_post.html', {'categories': categories, 'form': form})

def edit_post(request, post_id):
    categories = Category.objects.all()
    post = get_object_or_404(Post, id= post_id)

    if request.method == 'POST':
        form = NewPostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post.save()
            return redirect('blog:dashboard')
    return render(request, 'edit_post.html',{'categories': categories, 'post': post})

def delete_post(request, post_id):
    post = get_object_or_404(Post, id = post_id)
    post.delete()
    messages.success(request=request, message="Post deleted successfully")
    return redirect('blog:dashboard')

def publish_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post.is_published = True
    post.save()
    messages.success(request=request, message="Post published successfully")
    return redirect("blog:dashboard")

Blog/Blog/blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>
<body >

  {% include 'include/header.html' %}

    {% block content %}
    {% endblock %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
  {% include 'include/footer.html' %}
</body>
</html>

Blog/Blog/blog/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid ">
        <div class="row my-2">
            <div class="col">
                <h2 >{{Name | upper}} Posts</h2>
            </div>
            <div>
                {%include 'include/errors.html'%}
            </div>
            <div class="col-3">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search..." aria-label="Search">
                    <button class="btn btn-outline-light btn-primary " type="button" id="button-search">
                      <i class="bi bi-search"></i> <!-- Bootstrap Icons -->
                    </button>
                  </div>
            </div>
        </div>
        <div class="row m-3">
            {% for post in page_obj %}
            <div class="col-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                <img style="height:300" width:"300" src={{post.formatted_url}} class="img-fluid" alt="...">
                            </div>
                            <div class="col-md-8">
                                <h5 class="card-title">{{post.title}}</h5>
                                <p class="card-text">{{post.content}}</p>
                                <div class="d-flex justify-content-between">
                                     <a href="{% url "blog:details" post.slug %}">Read More</a>
                                    <a class="text-decoration-none text-dark fw-bold" href="#">{{post.category.name}}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="col-12 my-3">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1" aria-label="First">
                                <span aria-hidden="true">&laquo; first</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                                <span aria-hidden="true">previous</span>
                            </a>
                        </li>
                        {% endif %}
                        <li class="page-item"><span class="page-link">Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}</span></li>
                        {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                                <span aria-hidden="true">next</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.paginator.num_pages}}" aria-label="Last">
                                <span aria-hidden="true">last &raquo;</span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>

            </div>
        </div>
        <div class="row">

        </div>

    </div>

    {% endblock %}

Blog/Blog/blog/templates/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid">
        <div class="row d-flex justify-content-center mt-5">
            <div class="col-4">
                <h3>Login</h3>
                <div class="">
                    {% include 'include/errors.html' %}
                </div>
                <div class="my-3">
                    <form method="post">
                    {% csrf_token %}
                        <div class="form-group">
                            <label for="username" class="form-label">Username</label>
                            <input type="text" class="form-control" id="username" name="username" value={{form.username.value|default:""}}>
                        </div>
                       
                        <div class="form-group">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password">
                        </div>
                       
                        <div class="my-3 d-flex justify-content-between">
                            <a href="{% url 'blog:forgot_password' %}">Forgot Password</a>
                            <button type="submit" class="btn btn-primary">Login</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Blog/Blog/blog/templates/register.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid">
        <div class="row d-flex justify-content-center mt-5">
            <div class="col-4">
                <h3>Register</h3>
                <div class="">
                    {% include 'include/errors.html' %}
                </div>
                <div class="my-3">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username" class="form-label">Username</label>
                            <input type="text" class="form-control" id="username" name="username" value="{{form.username.value|default:""}}">
                        </div>
                        <div class="form-group">
                            <label for="email" class="form-label">Email</label>
                            <input type="email" class="form-control" id="email" name="email" value="{{form.email.value|default:""}}">
                        </div>
                        <div class="form-group">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password" value="">
                        </div>
                        <div class="form-group">
                            <label for="confirm_password" class="form-label">Confirm Password</label>
                            <input type="password" class="form-control" id="confirm_password" name="confirm_password">
                        </div>
                        <div class="my-3 d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">Register</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{%endblock%}